//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingtipToys.Admin
{


    public partial class Security
    {

        /// <summary>
        /// Control form1.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control TextBox1.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        /// <summary>
        /// Control Button1.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button1;

        /// <summary>
        /// Control Label1.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// Control CreateUserWizard1.
        /// </summary>
        protected global::System.Web.UI.WebControls.CreateUserWizard CreateUserWizard1;

        /// <summary>
        /// Control txtUser.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUser;

        /// <summary>
        /// Control btnAddToRole.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddToRole;

        /// <summary>
        /// Control lblStatus.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;
    }
}